Repository hassio-addons/addon-zwave-js-ui, pull requests merged in 2021-12, with the labels that each got.

#306 ⬆️ Upgrades nodejs to 16.13.1-r0
  zwavejs2mqtt/Dockerfile
Labels: dependencies

#307 ⬆️ Upgrades ZwaveJS2Mqtt to v6.0.3
  zwavejs2mqtt/Dockerfile
Labels: dependencies

#313 ⬆️ Upgrades ZwaveJS2Mqtt to v6.1.0
  zwavejs2mqtt/Dockerfile
Labels: dependencies

#312 Improve search-ability on Zwavejs2Mqtt
  zwavejs2mqtt/config.yaml
Labels: enhancement

#314 Update CI Workflows
  .github/workflows/ci.yaml
  .github/workflows/deploy.yaml
  .github/workflows/labels.yaml
  .github/workflows/lock.yaml
  .github/workflows/pr-labels.yaml
  .github/workflows/release-drafter.yaml
  .github/workflows/stale.yaml
Labels: ci

#316 ⬆️ Upgrades ZwaveJS2Mqtt to v6.1.1
  zwavejs2mqtt/Dockerfile
Labels: dependencies

#319 ⬆️Update zwavejs2mqtt to 6.2.0
  zwavejs2mqtt/Dockerfile
Labels: dependencies
