Repository hassio-addons/addon-zwave-js-ui, pull requests merged in 2021-05, with the labels that each got.

#158 Update database to a3d67de7d113c46460044ca3ecf01eb5c953cffc
  zwavejs2mqtt/Dockerfile
Labels: dependencies

#159 Fix hanging config update
  zwavejs2mqtt/Dockerfile
Labels: bugfix

#157 ⬆️ Upgrades ZwaveJS2Mqtt to v4.0.1
  zwavejs2mqtt/Dockerfile
Labels: dependencies

#169 ⬆️ Upgrades ZwaveJS2Mqtt to v4.2.1
  zwavejs2mqtt/Dockerfile
  zwavejs2mqtt/rootfs/etc/cont-init.d/configuration.sh
  zwavejs2mqtt/rootfs/etc/services.d/zwavejs2mqtt/run
Labels: dependencies, minor

#170 Clean up download of latest DB
  zwavejs2mqtt/Dockerfile
Labels: refactor

#173 ⬆️ Upgrades ZwaveJS2Mqtt to v4.3.0
  zwavejs2mqtt/Dockerfile
Labels: dependencies, minor

#176 ⬆️ Upgrades ZwaveJS2Mqtt to v4.3.1
  zwavejs2mqtt/Dockerfile
Labels: dependencies

#177 ⬆️ Upgrades ZwaveJS2Mqtt to v4.4.0
  zwavejs2mqtt/Dockerfile
Labels: dependencies, minor

#186 ⬆️ Upgrades add-on base image to v9.2.1
  zwavejs2mqtt/Dockerfile
  zwavejs2mqtt/build.json
Labels: dependencies

#183 ⬆️ Upgrades ZwaveJS2Mqtt to v4.5.0
  zwavejs2mqtt/Dockerfile
Labels: dependencies

#190 ⬆️ Upgrades ZwaveJS2Mqtt to v4.5.1
  zwavejs2mqtt/Dockerfile
Labels: dependencies
