Repository hassio-addons/addon-zwave-js-ui, pull requests merged in 2021-02, with the labels that each got.

#9 :arrow_up: Upgrades ZwaveJS2Mqtt to v1.0.2
  zwavejs2mqtt/Dockerfile
Labels: dependencies

#10 :arrow_up: Update ZwaveJS device database to b62505309ef31c4717d321a
  zwavejs2mqtt/Dockerfile
Labels: dependencies

#11 Upgrade add-on base image to 9.1.2
  zwavejs2mqtt/Dockerfile
  zwavejs2mqtt/build.json
Labels: dependencies

#13 :arrow_up: Upgrades ZwaveJS2Mqtt to v1.0.3
  zwavejs2mqtt/Dockerfile
Labels: dependencies

#15 Optionally expose WS port
  zwavejs2mqtt/config.json
Labels: new-feature

#18 :arrow_up: Update OpenZWave database to 76408b1623f966815c98a4b5ce581
  zwavejs2mqtt/Dockerfile
Labels: dependencies

#17 :arrow_up: Upgrades ZwaveJS2Mqtt to v1.0.5
  zwavejs2mqtt/Dockerfile
Labels: dependencies

#27 Update add-on configuration for Supervisor 2021.2
  .github/workflows/ci.yaml
  zwavejs2mqtt/config.json
Labels: maintenance

#28 :arrow_up: Upgrades ZwaveJS2Mqtt to v1.1.0
  zwavejs2mqtt/Dockerfile
Labels: dependencies, minor

#29 Update database to d86e9956f6b0160fcf675c2b3d33faed33dfba7c
  zwavejs2mqtt/Dockerfile
Labels: dependencies

#31 Enable udev
  zwavejs2mqtt/config.json
Labels: enhancement

#33 Update database to 6cc6466e2ce050b95364b1740cc6d123af3cdba1
  zwavejs2mqtt/Dockerfile
Labels: dependencies

#32 :arrow_up: Upgrades ZwaveJS2Mqtt to v1.1.1
  zwavejs2mqtt/Dockerfile
Labels: dependencies

#37 :arrow_up: Upgrades nodejs to 14.15.5-r0
  zwavejs2mqtt/Dockerfile
Labels: dependencies

#38 :arrow_up: Upgrades libusb to 1.0.24-r1
  zwavejs2mqtt/Dockerfile
Labels: dependencies

#39 Upgrade add-on base image to 9.1.3
  zwavejs2mqtt/Dockerfile
  zwavejs2mqtt/build.json
Labels: dependencies

#40 :arrow_up: Upgrades ZwaveJS2Mqtt to v1.2.0
  zwavejs2mqtt/Dockerfile
Labels: dependencies

#41 Update database to bcb1feca586b2fe1dc584283e548e1441d188547
  zwavejs2mqtt/Dockerfile
Labels: dependencies

#42 :arrow_up: Upgrades ZwaveJS2Mqtt to v1.2.1
  zwavejs2mqtt/Dockerfile
Labels: dependencies

#46 :arrow_up: Upgrades python3-dev to 3.8.7-r1
  zwavejs2mqtt/Dockerfile
Labels: dependencies

#48 :arrow_up: Upgrades ZwaveJS2Mqtt to v1.2.2
  zwavejs2mqtt/Dockerfile
Labels: dependencies

#49 Allow Supervisor to use health check for watchdog
  zwavejs2mqtt/config.json
Labels: enhancement

#50 Fix Watchdog URL to match Supervisor validation
  zwavejs2mqtt/config.json
Labels: bugfix

#55 :arrow_up: Upgrades ZwaveJS2Mqtt to v1.2.3
  zwavejs2mqtt/Dockerfile
Labels: dependencies

#59 ⬆️ Upgrades nodejs to 14.16.0-r0
  zwavejs2mqtt/Dockerfile
Labels: dependencies

#60 ⬆️ Upgrades ZwaveJS2Mqtt to v2.0.0
  zwavejs2mqtt/Dockerfile
Labels: dependencies, minor

#61 Update database to 23f96601431beb6c8b2bf88b6dcc580612d0fcd3
  zwavejs2mqtt/Dockerfile
Labels: dependencies
