Repository hassio-addons/addon-zwave-js-ui, pull requests merged in 2021-09, with the labels that each got.

#252 ⬆️ Upgrades nodejs to 14.17.6-r0
  zwavejs2mqtt/Dockerfile
Labels: dependencies

#253 ⬆️ Upgrades add-on base image to 10.1.0
  zwavejs2mqtt/Dockerfile
  zwavejs2mqtt/build.json
Labels: dependencies

#251 Upgrades ZwaveJS2Mqtt to v5.6.0
  zwavejs2mqtt/Dockerfile
Labels: minor, dependencies

#254 ⬆️ Upgrades ZwaveJS2Mqtt to v5.6.1
  zwavejs2mqtt/Dockerfile
Labels: dependencies

#255 🚑 Increase yarn network timeout for more consistent builds
  zwavejs2mqtt/Dockerfile
Labels: ci

#256 ⬆️ Upgrades ZwaveJS2Mqtt to v5.6.2
  zwavejs2mqtt/Dockerfile
Labels: dependencies

#257 ⬆️ Upgrades ZwaveJS2Mqtt to v5.7.0
  zwavejs2mqtt/Dockerfile
Labels: minor, dependencies

#258 ⬆️ Upgrades ZwaveJS2Mqtt to v5.7.1
  zwavejs2mqtt/Dockerfile
Labels: dependencies
