Repository hassio-addons/addon-zwave-js-ui, pull requests merged in 2022-06, with the labels that each got.

#384 :books: Use new My Home Assistant link format
  zwavejs2mqtt/DOCS.md
Labels: documentation

#389 ⬆️ Upgrades add-on base image to 12.2.0
  zwavejs2mqtt/Dockerfile
  zwavejs2mqtt/build.yaml
Labels: dependencies

#390 Update zwavejs2mqtt to 6.13.0
  zwavejs2mqtt/Dockerfile
Labels: minor, dependencies

#391 ⬆️ Upgrades nginx to 1.22.0-r1
  zwavejs2mqtt/Dockerfile
Labels: dependencies
