Repository hassio-addons/addon-zwave-js-ui, pull requests merged in 2022-10, with the labels that each got.

#426 ⬆️ Upgrades Z-Wave JS UI to v8.1.0
  zwave-js-ui/Dockerfile
Labels: dependencies

#432 ⬆️ Upgrades nodejs to 16.17.1-r0
  zwave-js-ui/Dockerfile
Labels: dependencies

#433 ⬆️ Upgrades nginx to 1.22.1-r0
  zwave-js-ui/Dockerfile
Labels: dependencies

#431 ⬆️ Upgrades Z-Wave JS UI to v8.2.1
  zwave-js-ui/Dockerfile
Labels: minor, dependencies

#419 Update DOCS.md
  zwave-js-ui/DOCS.md
Labels: documentation, in-progress, stale

#420 Fix typo in README
  README.md
Labels: documentation

#436 ⬆️ Upgrades Z-Wave JS UI to v8.2.2
  zwave-js-ui/Dockerfile
Labels: dependencies
