Repository hassio-addons/addon-zwave-js-ui, pull requests merged in 2022-01, with the labels that each got.

#327 ⬆️ Upgrades add-on base image to 11.0.1
  zwavejs2mqtt/Dockerfile
  zwavejs2mqtt/build.yaml
Labels: dependencies

#328 :fireworks: Updates maintenance/license year to 2022
  LICENSE.md
  README.md
  zwavejs2mqtt/.README.j2
  zwavejs2mqtt/DOCS.md
Labels: maintenance

#330 ⬆️ Upgrades ZwaveJS2Mqtt to v6.3.0
  zwavejs2mqtt/Dockerfile
Labels: minor, dependencies

#331 ⬆️ Upgrades ZwaveJS2Mqtt to v6.3.1
  zwavejs2mqtt/Dockerfile
Labels: dependencies

#336 ⬆️ Upgrades nodejs to 16.13.2-r0
  zwavejs2mqtt/Dockerfile
Labels: dependencies

#335 ⬆️ Upgrades ZwaveJS2Mqtt to v6.4.0
  zwavejs2mqtt/Dockerfile
Labels: dependencies

#337 ⬆️ Upgrades ZwaveJS2Mqtt to v6.4.1
  zwavejs2mqtt/Dockerfile
Labels: dependencies

#339 Fix upgrading firmware from Ingress
  zwavejs2mqtt/rootfs/etc/nginx/templates/ingress.gtpl
Labels: bugfix

#340 ⬆️ Upgrades ZwaveJS2Mqtt to v6.5.0
  zwavejs2mqtt/Dockerfile
Labels: minor, dependencies
