Repository hassio-addons/addon-zwave-js-ui, pull requests merged in 2022-12, with the labels that each got.

#448 ⬆️ Upgrades add-on base image to 13.0.0
  zwave-js-ui/Dockerfile
  zwave-js-ui/build.yaml
Labels: minor, dependencies

#449 :hammer: Migrate old-style base scripts s6-rc
  zwave-js-ui/Dockerfile
  zwave-js-ui/rootfs/etc/s6-overlay/s6-rc.d/discovery/dependencies.d/zwave-js-ui
  zwave-js-ui/rootfs/etc/s6-overlay/s6-rc.d/discovery/run
  zwave-js-ui/rootfs/etc/s6-overlay/s6-rc.d/discovery/type
  zwave-js-ui/rootfs/etc/s6-overlay/s6-rc.d/discovery/up
  zwave-js-ui/rootfs/etc/s6-overlay/s6-rc.d/init-nginx/dependencies.d/base
  zwave-js-ui/rootfs/etc/s6-overlay/s6-rc.d/init-nginx/run
  zwave-js-ui/rootfs/etc/s6-overlay/s6-rc.d/init-nginx/type
  zwave-js-ui/rootfs/etc/s6-overlay/s6-rc.d/init-nginx/up
  zwave-js-ui/rootfs/etc/s6-overlay/s6-rc.d/init-zwave-js-ui/dependencies.d/base
  zwave-js-ui/rootfs/etc/s6-overlay/s6-rc.d/init-zwave-js-ui/run
  zwave-js-ui/rootfs/etc/s6-overlay/s6-rc.d/init-zwave-js-ui/type
  zwave-js-ui/rootfs/etc/s6-overlay/s6-rc.d/init-zwave-js-ui/up
  zwave-js-ui/rootfs/etc/s6-overlay/s6-rc.d/nginx/dependencies.d/init-nginx
  zwave-js-ui/rootfs/etc/s6-overlay/s6-rc.d/nginx/dependencies.d/zwave-js-ui
  zwave-js-ui/rootfs/etc/s6-overlay/s6-rc.d/nginx/finish
  zwave-js-ui/rootfs/etc/s6-overlay/s6-rc.d/nginx/run
  zwave-js-ui/rootfs/etc/s6-overlay/s6-rc.d/nginx/type
  zwave-js-ui/rootfs/etc/s6-overlay/s6-rc.d/user/contents.d/discovery
  zwave-js-ui/rootfs/etc/s6-overlay/s6-rc.d/user/contents.d/init-nginx
  zwave-js-ui/rootfs/etc/s6-overlay/s6-rc.d/user/contents.d/init-zwave-js-ui
  zwave-js-ui/rootfs/etc/s6-overlay/s6-rc.d/user/contents.d/nginx
  zwave-js-ui/rootfs/etc/s6-overlay/s6-rc.d/user/contents.d/zwave-js-ui
  zwave-js-ui/rootfs/etc/s6-overlay/s6-rc.d/zwave-js-ui/dependencies.d/init-zwave-js-ui
  zwave-js-ui/rootfs/etc/s6-overlay/s6-rc.d/zwave-js-ui/finish
  zwave-js-ui/rootfs/etc/s6-overlay/s6-rc.d/zwave-js-ui/run
  zwave-js-ui/rootfs/etc/s6-overlay/s6-rc.d/zwave-js-ui/type
  zwave-js-ui/rootfs/etc/services.d/nginx/finish
  zwave-js-ui/rootfs/etc/services.d/zwave-js-ui/finish
Labels: maintenance

#450 ⬆️ Upgrades Z-Wave JS UI to v8.6.0
  zwave-js-ui/Dockerfile
Labels: minor, dependencies

#437 Remove duplicate reference to Zwave js ui
  README.md
Labels: documentation

#452 ⬆️ Upgrades Z-Wave JS UI to v8.6.1
  zwave-js-ui/Dockerfile
Labels: dependencies

#453 ⬆️ Upgrades Z-Wave JS UI to v8.6.2
  zwave-js-ui/Dockerfile
Labels: dependencies
