Repository hassio-addons/addon-zwave-js-ui, pull requests merged in 2022-09, with the labels that each got.

#408 ⬆️ Upgrades zwavejs2mqtt to 7.0.0
  zwavejs2mqtt/Dockerfile
Labels: dependencies

#411 Upgrades zwavejs2mqtt to 7.1.0
  zwavejs2mqtt/Dockerfile
Labels: dependencies

#412 ⬆️ Upgrades add-on base image to 12.2.4
  zwavejs2mqtt/Dockerfile
  zwavejs2mqtt/build.yaml
Labels: dependencies

#413 ⬆️ Upgrades zwavejs2mqtt to v7.2.0
  zwavejs2mqtt/Dockerfile
Labels: dependencies

#414 Update Home Assistant instructions
  zwavejs2mqtt/DOCS.md
Labels: documentation

#415 ⬆️ Upgrades Z-Wave JS UI to v8.0.0
  .github/CONTRIBUTING.md
  .github/workflows/ci.yaml
  .github/workflows/deploy.yaml
  README.md
  zwave-js-ui/.README.j2
  zwave-js-ui/DOCS.md
  zwave-js-ui/Dockerfile
  zwave-js-ui/build.yaml
  zwave-js-ui/config.yaml
  zwave-js-ui/icon.png
  zwave-js-ui/logo.png
  zwave-js-ui/rootfs/etc/cont-init.d/configuration.sh
  zwave-js-ui/rootfs/etc/cont-init.d/nginx.sh
  zwave-js-ui/rootfs/etc/nginx/includes/mime.types
  zwave-js-ui/rootfs/etc/nginx/includes/proxy_params.conf
  zwave-js-ui/rootfs/etc/nginx/includes/server_params.conf
  zwave-js-ui/rootfs/etc/nginx/includes/ssl_params.conf
  zwave-js-ui/rootfs/etc/nginx/includes/upstream.conf
  zwave-js-ui/rootfs/etc/nginx/nginx.conf
  zwave-js-ui/rootfs/etc/nginx/servers/.gitkeep
  zwave-js-ui/rootfs/etc/nginx/templates/ingress.gtpl
  zwave-js-ui/rootfs/etc/services.d/nginx/finish
  zwave-js-ui/rootfs/etc/services.d/nginx/run
  zwave-js-ui/rootfs/etc/services.d/zwave-js-ui/discovery
  zwave-js-ui/rootfs/etc/services.d/zwave-js-ui/finish
  zwave-js-ui/rootfs/etc/services.d/zwave-js-ui/run
  zwave-js-ui/translations/en.yaml
Labels: breaking-change, dependencies, major

#417 Mark project as production ready
  README.md
  zwave-js-ui/.README.j2
Labels: major, maintenance

#418 Fix broken link in add-on readme
  zwave-js-ui/.README.j2
Labels: documentation

#423 ⬆️ Upgrades Z-Wave JS UI to v8.0.1
  zwave-js-ui/Dockerfile
Labels: dependencies
