Repository hassio-addons/addon-zwave-js-ui, pull requests merged in 2023-03, with the labels that each got.

#473 ⬆️ Upgrades add-on base image to 13.1.3
  zwave-js-ui/Dockerfile
  zwave-js-ui/build.yaml
Labels: dependencies

#474 ⬆️ Upgrades Z-Wave JS UI to v8.9.0
  zwave-js-ui/Dockerfile
Labels: dependencies

#475 Fix typo in README
  zwave-js-ui/.README.j2
Labels: documentation

#476 :broom: Clean up left over from old discovery
  zwave-js-ui/rootfs/etc/s6-overlay/s6-rc.d/zwave-js-ui/run
Labels: maintenance

#480 ⬆️ Upgrades Z-Wave JS UI to v8.10.0
  zwave-js-ui/Dockerfile
Labels: dependencies

#481 ⬆️ Upgrades Z-Wave JS UI to v8.10.1
  zwave-js-ui/Dockerfile
Labels: dependencies

#488 Add Renovate for dependency management
  .github/dependabot.yaml
  .github/renovate.json
  zwave-js-ui/Dockerfile
Labels: maintenance

#495 Fix broken URL
  zwave-js-ui/DOCS.md
Labels: documentation
